### ISSUE TITLE
Got error CentOS5.8

### ISSUE THREAD

**Issue by fxfred** [scalp42/python-2.7.x-on-Centos-5.x#1]
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

building 'Crypto.Hash._MD2' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/opt/python2.7.2/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o

gcc -pthread -shared build/temp.linux-x86_64-2.7/src/MD2.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/Crypto/Hash/_MD2.so

/usr/bin/ld: cannot find -lpython2.7

collect2: ld returned 1 exit status

error: command 'gcc' failed with exit status 1

---

Command /usr/bin/python2.7 -c "import setuptools;**file**='/tmp/build/pycrypto/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-rY4ydf-record/install-record.txt failed with error code 1 in /tmp/build/pycrypto
## French maid time... let's clean everything.

---
## Let's create some links for empty bash profile users out there.

./install_python27.sh: line 125: unexpected EOF while looking for matching `"'
./install_python27.sh: line 126: syntax error: unexpected end of file

**Comment by scalp42** [comment]
Fred,

What version of CentOS are you using ?

Could you make sure you have python-devel installed ? Sounds like PyCrypto cant get installed.

I'll look into it, might try to replace pip with easy_install in the meantime.

**Comment by fxfred** [comment]
Hi Anthony,

It's 5.8
I can see a python2.7 in /usr/bin. It's Python 2.7.2.

Thanks
Fred

On Sun, Jul 1, 2012 at 10:48 PM, Anthony Scalisi
reply@reply.github.com
wrote:

> Fred,
> 
> What version of CentOS are you using ?
> 
> Could you make sure you have python-devel installed ? Sounds like PyCrypto cant get installed.
> 
> I'll look into it, might try to replace pip with easy_install in the meantime.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/scalp42/python-2.7.2-on-Centos-5.x/issues/1#issuecomment-6699549

## 

Fred Xiang

**Comment by scalp42** [comment]
It means it got perfectly installed.

The error you're seeing is not directly related to Python 2.7.2 but to pip and the install of Fabric (which is not really needed).

try typing 

#> pip install fabric virtualenv

to see if you get the same error message. If yes just replace with 

#> easy_install fabric

might help.

I will fire up a vm when I get the chance and dig into it.

**Comment by scalp42** [comment]
Also worth trying :

#> yum install python-setuptools-devel
#> yum install python-setuptools

#> easy_install pycrypto 

and try again

#> easy_install fabric

But again, Fabric is used for deployment. If it's not needed, feel free to skip it!

**Comment by scalp42** [comment]
@fxfred, I fired a clean CentOS 5.8 VM and executed the script straight out-of-the-box. Didn't run into any issues (you can find the log here : https://gist.github.com/3049922 )

Please clone and execute the script again (the repo name changed as well).

I fixed all the problems and it has been updated to install python 2.7.3.

Thank you a lot for your input !!

**Comment by fxfred** [comment]
Thank you Anthony,

I changed the python link to 2.7.2 and did the job, then changed it
back to 2.4.3. It worked for me already.
Thank you very much.

--Fred

On Wed, Jul 4, 2012 at 6:46 PM, Anthony Scalisi
reply@reply.github.com
wrote:

**Comment by scalp42** [comment]
Remember that python is still 2.4.3 but python27 is 2.7.3.

Thanks for the feedback. Closing the issue.

Enjoy,

Anthony
