### ISSUE TITLE
Script does not create /opt/bin when needed

### ISSUE THREAD

**Issue by Blaisorblade** [scalp42/python-2.7.x-on-Centos-5.x#10]
On my system `/opt/bin` does not exist, but the script tries to use it anyway and fails.
I think that

``` bash
mkdir -p ${dest}/bin || { echo "Failed because..."; exit 1; }
```

would solve the problem.

Then, it prints

```
Looks like the script exited or got interrupted, cleaning up.
```

But it gives no idea whether the script succeeded or failed. In fact, the first thing I tried was launching the script again after creating `/opt/bin`, but that restarted the whole compilation process, not what I expected.

**Comment by scalp42** [comment]
Hi @Blaisorblade,

The script should not try to create `/opt/bin/`, but `/opt/python$version/bin`.

As you can see, during compilation:

```
 ./configure --prefix=${dest}/python$python2vers
```

Could you have a look at the `/opt/` directory and see any `python` folder please ?

Just making sure, but run a `git pull` in the project as well.

**Comment by scalp42** [comment]
Hey @Blaisorblade,

So I updated the README and the script a little bit. 

FYI, python was installed correctly. The "error" you see is related to Fabric and extras being installed:

```
ln -s ${dest}/python$python2vers/bin/fab ${dest}/bin/fab
```

I personally like to have my binaries in one place, and you either can export the paths or symlink them in `/usr/local/bin` for example.

I removed the symlinks from the script, and you should not see any misleading error from now on.

Also, "restarting the whole compilation process" is something intended so it's easier to debug.

Let me know if you have any other issues please and if not, they will be closed by the end of the week,

Thanks!

**Comment by Blaisorblade** [comment]
Hi @scalp42, thanks a lot for the quick answer! I can't see the changes on the master branch, the last commit is still from 13 days ago. Please let me know when you push the changes.

**Comment by scalp42** [comment]
Changes have been pushed to master branch

https://github.com/scalp42/python-2.7.x-on-Centos-5.x/pull/12

Thanks!

**Comment by scalp42** [comment]
Alternatively,

Setting in the script

```
install_extras="false"
```

will skip Virtualenv, Fabric etc.

**Comment by Blaisorblade** [comment]
The code looks good, thanks :-)! I don't have time yet to retest this right now, but please feel free to consider it closed.

**Comment by scalp42** [comment]
Danke!
