### ISSUE TITLE
README.md is inconsistent: Was the script tested on 5.5 or 5.8?

### ISSUE THREAD

**Issue by Blaisorblade** [scalp42/python-2.7.x-on-Centos-5.x#11]
At different locations, `README.md` claims that the script was tested on 5.5-5.7, or 5.6-5.8. Such apparent mistakes don't make me trust so much a script which I'm supposed to run as root anyway.

FYI, I run the script on 5.9 almost successfully - except for #10.

However, thanks for this repo anyway - the problems I found seem (up to now) mostly minor.

**Comment by scalp42** [comment]
Hi Blaisorblade,

I tested the script on the versions mentioned and you should have a look at the Vagrantfile.

Also, you should not trust any script whatsoever, which is why I provided a small Vagrantfile so you can have an idea with what's happening.

That being said, I'm about to test it on 5.8 again and will get back to you with what I found.

**Comment by scalp42** [comment]
Script was tested on minimal CentOS 5.8 x86_64 and I updated the Vagrantfile to reflect the testing.

https://github.com/scalp42/python-2.7.x-on-Centos-5.x/pull/12

**Comment by Blaisorblade** [comment]
Thanks a lot for your prompt response!

I never heard of Vagrant before, but it seems rather cool (I'm trying it out now). However, users of this repository might not notice that file or be able to figure it out without a mention in the `README.md`.

**Comment by scalp42** [comment]
hey @Blaisorblade,

Unfortunately, it would be too cumbersome to explain every file in this repository. I only want to focus on the script, as it should not really matter that you know about the Vagrantfile or Gemfile for example.

It's just included to make it easier for you to test, but could be totally removed from the repo.

The script is meant to be self-contained and technically executed through something like this:

```
#> curl https://raw.github.com/scalp42/python-2.7.x-on-Centos-5.x/master/install_python27.sh | bash
```

I'll close the issue as I consider it fixed (`README.md` has been updated).

Thanks again!
