### ISSUE TITLE
wrong python URL

### ISSUE THREAD

**Issue by boypt** [scalp42/python-2.7.x-on-Centos-5.x#14]
on the line retrieving python URL: 

`curl -m 5 --silent www.askcerebro.com/python/python2/url`

guess what returned,  `http://www.python.org/ftp/python/2.7.5/Python-2.7.6.tgz`

which will never work.

**Comment by scalp42** [comment]
@pentie the bug should be fixed now: https://github.com/scalp42/askcerebro/pull/65

[http://www.askcerebro.com/python](http://www.askcerebro.com/python)

Thanks for reporting it.

**Comment by scalp42** [comment]
I'm gonna close this issue, please reopen if you run into any problems.

Thanks!
