### ISSUE TITLE
./configure: /bin/bash: bad interpreter: Permission denied

### ISSUE THREAD

**Issue by asabaylus** [scalp42/python-2.7.x-on-Centos-5.x#15]
When exec is not allowed on the mount ./configure will raise the following error
`./configure: /bin/bash: bad interpreter: Permission denied`

Using "/tmp" will allow the compiler to run on systems which dont permit access to fstab
See: http://forums.fedoraforum.org/archive/index.php/t-19374.html

**Comment by scalp42** [comment]
Thanks for reporting the issue @asabaylus 

I'll take a look.

**Comment by scalp42** [comment]
@asabaylus mind telling what OS you're using, the arch, and the output of `python -V` please.

**Comment by asabaylus** [comment]
SolarVPS using CentOS release 5.10 (Final)
Linux version 2.6.18-348.16.1.el5xen (mockbuild@builder10.centos.org) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-54))

I've created a pull request #19 for the fix
Please note that I had to switch to "/tmp" I'm not sure if that dir is standard.
So I'm now happily running Python 2.7.6
