### ISSUE TITLE
Error CentOS 5.8

### ISSUE THREAD

**Issue by akd3vs** [scalp42/python-2.7.x-on-Centos-5.x#2]
This is the last part of the log

```
./install_python27.sh: line 80: cd: /opt/python2.7/lib/python2.7/config: No existe el fichero o el directorio (doesn't exists the file or directory)
ln: creando el enlace simbólico (creating symlink) «./libpython2.7.so» a «../../libpython2.7.so»: El fichero ya existe (the file already exists)
TEST FAILED: /opt/python2.7.2/lib/python2.7/site-packages does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /opt/python2.7.2/lib/python2.7/site-packages

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  http://peak.telecommunity.com/EasyInstall.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
./install_python27.sh: line 85: /opt/python2.7.2/bin/easy_install: No existe el fichero o el directorio(doesn't exists the file or directory)
./install_python27.sh: line 88: /opt/python2.7.2/bin/easy_install: No existe el fichero o el directorio(doesn't exists the file or directory)
./install_python27.sh: line 91: /opt/python2.7.2/bin/easy_install: No existe el fichero o el directorio(doesn't exists the file or directory)
----------------------------------------------------
French maid time... let's clean everything.
----------------------------------------------------

----------------------------------------------------
Let's create some links for empty bash profile users out there.
----------------------------------------------------


Done !
```

The previous python was 2.4.3 and I was trying to compile python 2.7.3 but I could not. The files are in /usr/local/bin and /usr/local/lib (the default paths)

**Comment by scalp42** [comment]
@akd3vs, I fired a clean CentOS 5.8 and executed the script straight out-of-the-box. Didn't run into any issues (please find the log here : https://gist.github.com/3049922 )

Please clone and execute the script again (the repo name changed as well).

I fixed all the problems and it has been updated to install python 2.7.3.

Thank you a lot for your input !!

**Comment by akd3vs** [comment]
It doesn't work :( https://gist.github.com/3053819

**Comment by scalp42** [comment]
I will look into it but couple things real quick :

1) You have Python 2.7.3 installed.

2) From now on, no need to re run the script, just need to get easy_install working

3) Try :

cd /tmp
wget http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg 
sh /tmp/setuptools-0.6c11-py2.7.egg --prefix=/opt/python2.7.3 --install-dir=/opt/python2.7.3/lib/python2.7/site-packages

4) Try without specifying the prefix :

sh setuptools-0.6c9-py2.4.egg

Will report with what I find.

Thanks!

**Comment by akd3vs** [comment]
with prefix says the same as the script.
without the prefix says

```
Processing setuptools-0.6c11-py2.7.egg
Copying setuptools-0.6c11-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding setuptools 0.6c11 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Installing easy_install-2.7 script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg
Processing dependencies for setuptools==0.6c11
Finished processing dependencies for setuptools==0.6c1
```

**Comment by scalp42** [comment]
I was just trying to keep binaries in the same folder /opt/python2.7.3/bin 

But besides this, you're all set up. I could not replicate your error on a clean VM.

Just go ahead and run : 

sudo /usr/local/bin easy_install pip

And then pip install fabric

**Comment by akd3vs** [comment]
https://gist.github.com/3054899

**Comment by scalp42** [comment]
python IS 2.4.3 (needed to not break yum)

python27 is 2.7.3.

So you're all set up.

**Comment by akd3vs** [comment]
Thank you very much for the support! :)
What I needed python 2.7 is for compile Node.js. What I did is
rm /usr/bin/python && ln -s /opt/python2.7.3/bin/python2.7 /usr/bin/python
and the compilation succeded .
Now 
rm /usr/bin/python && ln -s /usr/bin/python2.4 /usr/bin/python
Thank you!

P.D Sorry for my English

**Comment by scalp42** [comment]
Thanks for the feedback, closing the issue.
