### ISSUE TITLE
 installing python 2.7 on centos 5.8

### ISSUE THREAD

**Issue by gudge25** [scalp42/python-2.7.x-on-Centos-5.x#3]
When i execute your script>
line 87: syntax error near unexpected token `&&'
line 87:`&&' 

1)uname -a
Linux europa.fm 2.6.32-4-pve #1 SMP Fri Nov 26 06:42:28 CET 2010 i686 i686 i386 GNU/Linux
2)whish bash
/bin/bash

chmod a+x install.sh
./install.sh (user=root)

**Comment by tank064** [comment]
hi ! After executing your shell script , then i enter python 2.7.3 , but i found i could not use 'del' key to delete wrong-inputed characters !

and  i'm a python freshman , could you tell me how to install zlib module when compiling python , (cas after i extract Python-2.7.3.tgz , i found sth. like zlib , then i think that it may be install zlib module when compiling python.)

Waiting for your answer !

**Comment by scalp42** [comment]
Hey @tank064,

Zlib and readline should ship by default on Linux. Could you provide some information regarding your system please ?

I might be able to help.

**Comment by scalp42** [comment]
Closing as it's too old.
