### ISSUE TITLE
sqlite-autoconf URL 404's and the library paths used to update ldconfig point to a directory that doesn't exist

### ISSUE THREAD

**Issue by tthayer** [scalp42/python-2.7.x-on-Centos-5.x#8]
I've updated the pertinent parts of the script in my fork. Feel free to pull the changes in if you like.
https://github.com/tthayer/python-2.7.x-on-Centos-5.x/commit/75f196ae42d4b61b29aed2f52d53569c19d9241b#install_python27.sh

**Comment by scalp42** [comment]
Hey @tthayer,

Looks like I messed up the URL indeed.

Thanks for contributing. I merged your commit and mentioned you in the `README`.

Thanks again!

Pull request is https://github.com/scalp42/python-2.7.x-on-Centos-5.x/pull/9
